### ISSUE TITLE
A NullReferenceException error appears when dealing with UnityEvent field.

### ISSUE THREAD

**Issue by Elezor** [ChemiKhazi/ReorderableInspector#2]
**Reproduction:**
1.Create a public UnityEvent type field in any script.
2.Attach this script to a gameObject of the scene.
3.Popup the error.

**Solution(I GUESS):**
Check if the object parameter is null at the first line of GetValue method.

**Comment by ChemiKhazi** [comment]
Thanks for the report, will look into this when I can.

**Comment by ChemiKhazi** [comment]
Fix was simple enough, thanks for the report.
